apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: knative-sources
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/event_display
